routes/web.php
    $previousUrl = app('url')->previous();
    $exp=explode('?',$previousUrl);

    return redirect()->to($exp[0].'?'. http_build_query(['lang'=> $locale]));
});

Route::GET('transfer_data','ClientController@transfer_data');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


Route::GET('/','ClientController@index');
Route::GET('/about-party','ClientController@about');
Route::GET('/party-structure','ClientController@party_structure');
Route::GET('/party-council','ClientController@party_council');
Route::GET('/party-regulation','ClientController@party_regulation');
Route::GET('/bulletin','ClientController@bulletin');
Route::GET('/news','ClientController@news');
Route::GET('/candidates','ClientController@candidates');
Route::GET('/mayor','ClientController@mayor');
Route::GET('/show-mayor/{id}/{param}','ClientController@show_mayor');

Route::GET('/region-program','ClientController@region_program');
Route::GET('/show-region-program/{id}/{param}','ClientController@show_region_program');



Route::GET('/program','ClientController@program');
Route::GET('/world-media','ClientController@world_media');
Route::GET('/show-world-media/{id}/{param}','ClientController@show_world_media');
Route::GET('/show-candidates/{id}/{param}','ClientController@show_candidates');
Route::GET('/show-structure/{id}/{param}','ClientController@show_structure');

Route::GET('/video-gallery','ClientController@video_gallery');
Route::get('/show-photo-gallery/{id}','ClientController@show_photo_gallery');
Route::GET('/photo-gallery','ClientController@photo_gallery');
Route::GET('/contact','ClientController@contact');
Route::GET('/contact_send','ClientController@contact_send');

Route::GET('/young','ClientController@young');
Route::GET('/transfers','ClientController@transfers');
Route::GET('/search','ClientController@search');
Route::GET('/show-bulletin/{id}/{param}','ClientController@show_bulletin');

Route::GET('/show-news/{id}/{param}','ClientController@show_news');
Route::GET('/proportional','ClientController@proportional');
Route::GET('/show-bio/{id}/{param}','ClientController@show_bio');


Route::GET('/programs','ClientController@programs');


View::composer('website.layouts.app', function($view){
    $settings=\App\Models\DefaultSettingsModel::first();
    $view->with('settings',$settings);
});


Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);


    Route::POST('proportional_list/delete_proportional_list_picture','Admin\ProportionalController@delete_proportional_list_picture');
    Route::post('proportional_list/uploadFiles','Admin\ProportionalController@uploadFiles');
    Route::resource('proportional_list','Admin\ProportionalController');

    Route::POST('majoritarians/delete_majoritarians_picture','Admin\MajoritariansController@delete_majoritarians_picture');
    Route::post('majoritarians/uploadFiles','Admin\MajoritariansController@uploadFiles');
    Route::resource('majoritarians','Admin\MajoritariansController');


    Route::POST('mayor/delete_mayor_picture','Admin\mayorController@delete_mayor_picture');
    Route::post('mayor/uploadFiles','Admin\mayorController@uploadFiles');
    Route::resource('mayor','Admin\mayorController');


    Route::POST('region/get_districts','Admin\RegionController@get_districts');
    Route::POST('region/delete_district','Admin\RegionController@delete_district');
    Route::POST('region/update_district','Admin\RegionController@update_district');
    Route::POST('region/edit_district','Admin\RegionController@edit_district');
    Route::POST('region/save_district','Admin\RegionController@save_district');
    Route::get('region/add_district/{id}','Admin\RegionController@add_district');
    Route::resource('region','Admin\RegionController');

    Route::resource('default_settings','Admin\DefaultSettingsController');

    Route::POST('political_party/Sort','Admin\PoliticalPartyController@Sort');
    Route::POST('political_party/delete_politican_party_picture','Admin\PoliticalPartyController@delete_politican_party_picture');
    Route::POST('political_party/delete_other_position','Admin\PoliticalPartyController@delete_other_position');
    Route::POST('political_party/update_other_position','Admin\PoliticalPartyController@update_other_position');
    Route::POST('political_party/edit_other_position','Admin\PoliticalPartyController@edit_other_position');
    Route::POST('political_party/save_other_position','Admin\PoliticalPartyController@save_other_position');
    Route::GET('political_party/add_positions/{id}','Admin\PoliticalPartyController@add_positions');
    Route::post('political_party/uploadFiles','Admin\PoliticalPartyController@uploadFiles');
    Route::resource('political_party','Admin\PoliticalPartyController');

    Route::post('rules/uploadFiles','Admin\RulesController@uploadFiles');
    Route::resource('rules','Admin\RulesController');

    Route::post('about/uploadFiles','Admin\AboutController@uploadFiles');
    Route::resource('about','Admin\AboutController');


    Route::POST('media/delete_picture','Admin\MediaController@delete_picture');
    Route::POST('media/pin_home','Admin\MediaController@pin_home');
    Route::post('media/uploadFiles','Admin\MediaController@uploadFiles');
    Route::resource('media','Admin\MediaController');


    Route::POST('bulletin/pause-news','Admin\BulletinController@pause_news');
    Route::POST('bulletin/pin_to_slide','Admin\BulletinController@pin_to_slide');
    Route::POST('bulletin/delete_picture','Admin\BulletinController@delete_picture');
    Route::POST('bulletin/delete_attachment','Admin\BulletinController@delete_attachment');
    Route::POST('bulletin/pin_home','Admin\BulletinController@pin_home');
    Route::post('bulletin/uploadFiles','Admin\BulletinController@uploadFiles');
    Route::post('bulletin/uploadNewFiles','Admin\BulletinController@uploadNewFiles');
    Route::resource('bulletin','Admin\BulletinController');




    Route::POST('news/pause-news','Admin\NewsController@pause_news');
    Route::POST('news/pin_to_slide','Admin\NewsController@pin_to_slide');
    Route::POST('news/delete_picture','Admin\NewsController@delete_picture');
    Route::POST('news/delete_attachment','Admin\NewsController@delete_attachment');
    Route::POST('news/pin_home','Admin\NewsController@pin_home');
    Route::post('news/uploadFiles','Admin\NewsController@uploadFiles');
    Route::post('news/uploadNewFiles','Admin\NewsController@uploadNewFiles');
    Route::resource('news','Admin\NewsController');



    Route::POST('region_programe/pause-news','Admin\RegionPrograme@pause_news');
    Route::POST('region_programe/pin_home','Admin\RegionPrograme@pin_home');

    Route::POST('region_programe/delete_picture','Admin\RegionPrograme@delete_picture');
    Route::POST('region_programe/delete_attachment','Admin\RegionPrograme@delete_attachment');
    Route::post('region_programe/uploadFiles','Admin\RegionPrograme@uploadFiles');
    Route::post('region_programe/uploadNewFiles','Admin\RegionPrograme@uploadNewFiles');
    Route::resource('region_programe','Admin\RegionPrograme');


    Route::post('about/uploadFiles','Admin\AboutController@uploadFiles');
    Route::post('about/uploadHeaderFiles','Admin\AboutController@UploadHeaderFile');
    Route::resource('about','Admin\AboutController');

    Route::post('slider/uploadFiles','Admin\SliderController@uploadFiles');
    Route::resource('slider','Admin\SliderController');


    Route::post('transfers/uploadFiles','Admin\TransfersController@uploadFiles');
    Route::POST('transfers/uploadIconFiles','Admin\TransfersController@uploadIconFiles');
    Route::POST('transfers/delete_file','Admin\TransfersController@delete_file');
    Route::POST('transfers/delete_icon','Admin\TransfersController@delete_icon');
    Route::resource('transfers','Admin\TransfersController');


    Route::post('young/uploadFiles','Admin\YoungController@uploadFiles');
    Route::resource('young','Admin\YoungController');

    Route::POST('photo_gallery/delete_picture','Admin\PhotoGalleryController@delete_picture');
    Route::post('photo_gallery/uploadFiles','Admin\PhotoGalleryController@uploadFiles');
    Route::resource('photo_gallery','Admin\PhotoGalleryController');



    Route::resource('video_gallery','Admin\VideoGalleryController');

    Route::get('programs/delete','Admin\ProgramsController@delete');
    Route::post('programs/uploadFiles','Admin\ProgramsController@uploadFiles');

app/Http/Controllers/Admin/MajoritariansController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\MajoritariansModel;
use App\Models\RegionModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class MajoritariansController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $political_party=MajoritariansModel::orderby('id','desc');

        if(isset($request->fname) && $request->fname!=''){
            $political_party->where('name_ge','like','%'.$request->fname.'%');
        }

        if(isset($request->region) && $request->region!=''){
            $political_party->where('region_id','=',$request->region);
        }





        $data['political_party']=$political_party->paginate(15);
        $data['region']=RegionModel::get();
        return view('admin.majoritarians.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'form' => [
                'method' => 'POST',
                'action' => '/admin/majoritarians'
            ]
        ];
        $data['region']=RegionModel::get();
        return view('admin.majoritarians.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [

            'image'=>'required',
            'name_ge'=>'required',

        ]);

/*
        "name_ge" => "test"
      "name_en" => "test"
      "majoritarian_percent" => "test"
      "cesco_link" => "test"
      "region" => "2"
      "district" => "2"
      "work_ge" => "<p>test</p>"
      "work_en" => "<p>test</p>"
      "education_ge" => "<p>test</p>"
      "education_en" => "<p>test</p>"
      "facebook" => "test"
      "instagram" => "test"
      "twitter" => "test"
      "youtube" => "test"
      "image" => "bcae5f6b4b8cc1b5c.png"
      "image_real_name" => "Screen Shot 2020-09-11 at 11.47.55 AM.png"*/

        $political_party=new MajoritariansModel();
        $political_party->name_ge=$request->name_ge;
        $political_party->name_en=$request->name_en;


        $political_party->majoritarian_percent=$request->majoritarian_percent;
        $political_party->cesco_link=$request->cesco_link;
        $political_party->region_id=$request->region;

        $political_party->location_ge=$request->location_ge;
        $political_party->location_en=$request->location_en;


        $political_party->district_id=$request->district;
        $political_party->work_ge=$request->work_ge;
        $political_party->work_en=$request->work_en;
        $political_party->education_ge=$request->education_ge;
        $political_party->education_en=$request->education_en;
        $political_party->picture=$request->image;
        $political_party->facebook=$request->facebook;
        $political_party->twitter=$request->twitter;
        $political_party->instagram=$request->instagram;
        $political_party->youtube=$request->youtube;
        $political_party->user_id=Auth::user()->id;
        $political_party->save();


        return redirect(url('admin/majoritarians'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'form' => [
                'method' => 'POST',
                'action' => '/admin/majoritarians/'.$id,
                'id'=>$id

            ]
        ];

        $data['news']=MajoritariansModel::where('id',$id)->first();
        $data['region']=RegionModel::get();
        return view('admin.majoritarians.create',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [

            'image'=>'required',
            'name_ge'=>'required',

        ]);

        /*
                "name_ge" => "test"
              "name_en" => "test"
              "majoritarian_percent" => "test"
              "cesco_link" => "test"
              "region" => "2"
              "district" => "2"
              "work_ge" => "<p>test</p>"
              "work_en" => "<p>test</p>"
              "education_ge" => "<p>test</p>"
              "education_en" => "<p>test</p>"
              "facebook" => "test"
              "instagram" => "test"
              "twitter" => "test"
              "youtube" => "test"
              "image" => "bcae5f6b4b8cc1b5c.png"
              "image_real_name" => "Screen Shot 2020-09-11 at 11.47.55 AM.png"*/

        $political_party=MajoritariansModel::where('id',$id)->first();
        $political_party->name_ge=$request->name_ge;
        $political_party->name_en=$request->name_en;


        $political_party->majoritarian_percent=$request->majoritarian_percent;
        $political_party->cesco_link=$request->cesco_link;
        $political_party->region_id=$request->region;
        $political_party->location_ge=$request->location_ge;
        $political_party->location_en=$request->location_en;


        $political_party->district_id=$request->district;
        $political_party->work_ge=$request->work_ge;
        $political_party->work_en=$request->work_en;
        $political_party->education_ge=$request->education_ge;
        $political_party->education_en=$request->education_en;
        $political_party->picture=$request->image;
        $political_party->facebook=$request->facebook;
        $political_party->twitter=$request->twitter;
        $political_party->instagram=$request->instagram;
        $political_party->youtube=$request->youtube;
        $political_party->user_id=Auth::user()->id;
        $political_party->save();


        return redirect(url('admin/majoritarians'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete=MajoritariansModel::where('id',$id)->delete();
        return back();
    }
    public function uploadFiles(Request $request){
        $image = $request->file('file');
        $imageName = uniqid(substr(hash('sha256', $image->getClientOriginalName()), 0, 4)).'.'.$image->getClientOriginalExtension();
        $image->move(public_path('uploads/majoritarians'),$imageName);

        return [
            'success' => $imageName,
            'real_name'=>$image->getClientOriginalName()
        ];

    }
    public function delete_majoritarians_picture(Request $request){
        $data=MajoritariansModel::where('id',$request->id)->first();
        $data->picture='';
        $data->save();

    }
}

resources/views/admin/majoritarians/create.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <div class="page-wrapper">


        <div class="container-fluid">
            <h3 class="page-title">მაჟორიტარების დამატება</h3>


            <div class="row">
                <div class="col-12">
                    <!-- Column -->
                    <div class="card">

                        <div class="card-body table-responsive">


                            <form method="{{ $form['method'] }}" action="{{ $form['action'] }}">

                                {{ csrf_field() }}

                                @if(isset($form['id']))
                                    {{ method_field('PUT') }}
                                @endif


                                <div class="row">
                                    <div class="col-md-6 mt-2">

                                        @if($errors->has('name_ge'))
                                            <label style="color:red;">სახელი გვარი ქართულად</label>
                                        @else
                                            <label>სახელი გვარი ქართულად</label>
                                        @endif
                                        <input type="text" value="{{ $news->name_ge or '' }} {{ old('name_ge') ? old('name_ge') : '' }}" name="name_ge"  class="form-control">

                                    </div>

                                    <div class="col-md-6 mt-2">

                                        <label>სახელი გვარი ინგლისურად</label>
                                        <input type="text" value="{{ $news->name_en or '' }} {{ old('name_en') ? old('name_en') : '' }}" name="name_en"  class="form-control">

                                    </div>


                                    <div class="col-md-6 mt-2">

                                        @if($errors->has('name_ge'))
                                            <label style="color:red;">რაიონი ქართულად</label>
                                        @else
                                            <label>რაიონი ქართულად</label>
                                        @endif
                                        <input type="text" value="{{ $news->location_ge or '' }} {{ old('location_ge') ? old('location_ge') : '' }}" name="location_ge"  class="form-control">

                                    </div>

                                    <div class="col-md-6 mt-2">

                                        <label>რაიონი ინგლისურად</label>
                                        <input type="text" value="{{ $news->location_en or '' }} {{ old('location_en') ? old('location_en') : '' }}" name="location_en"  class="form-control">

                                    </div>





                                    <div class="col-md-6 mt-2">

                                        @if($errors->has('position_ge'))
                                            <label style="color:red;">მაჟორიტარის პროცენტი</label>
                                        @else
                                            <label>მაჟორიტარის პროცენტი</label>
                                        @endif
                                        <input type="text" value="{{ $news->majoritarian_percent or '' }} {{ old('majoritarian_percent') ? old('majoritarian_percent') : '' }}" name="majoritarian_percent"  class="form-control">

                                    </div>

                                    <div class="col-md-6 mt-2">

                                        <label>ცესკო-ს ლინკი</label>
                                        <input type="text" value="{{ $news->cesco_link or '' }} {{ old('cesco_link') ? old('cesco_link') : '' }}" name="cesco_link"  class="form-control">

                                    </div>

                                </div>


                                <div class="row mt-2">
                                    <div class="col-md-6">
                                        <label>რეგიონი</label>
                                        <select class="form-control region" name="region">
                                            <option value="">აირჩიეთ რეგიონი</option>
                                            @foreach($region as $row)
                                                <option value="{{ $row->id }}" {{ isset($news->region_id) && $row->id == $news->region_id ? "selected" : "" }}>{{ $row->name_ge }}</option>
                                            @endforeach

                                        </select>
                                    </div>
                                    <div class="col-md-6 {{ isset($news->district_id) ? "d-block" : "d-none" }} district_block">
                                        <label>რაიონი</label>
                                        <select class="form-control  district" name="district">
                                            <option value="">აირჩიეთ რაიონი</option>
                                            @if(isset($news->district_id))
                                            @foreach($news->Region->District as $row)

                                                <option value="{{ $row->id }}" {{ isset($news->district_id) && $row->id == $news->district_id ? "selected" : "" }}>{{ $row->name_ge }}</option>
                                            @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>






                                <div class="row">
                                    <div class="col-md-6 mt-2">

                                        @if($errors->has('work_ge'))
                                            <label style="color:red;">სამუშაო გამოცდილება ქართულად</label>
                                        @else
                                            <label>სამუშაო გამოცდილება  ქართულად</label>
                                        @endif
                                        <textarea name="work_ge" id="mymce" class="form-control">{{ old('work_ge') ? old('work_ge') : '' }}{{ $news->work_ge or '' }}</textarea>

                                    </div>

                                    <div class="col-md-6 mt-2">

                                        <label>სამუშაო გამოცდილება ინგლისურად</label>
                                        <textarea name="work_en" id="mymce" class="form-control">{{ old('work_en') ? old('work_en') : '' }}{{ $news->work_en or '' }}</textarea>

                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-md-6 mt-2">

                                        @if($errors->has('work_ge'))
                                            <label style="color:red;">განათლება ქართულად</label>
                                        @else
                                            <label>განათლება  ქართულად</label>
                                        @endif
                                        <textarea name="education_ge" id="mymce" class="form-control">{{ old('education_ge') ? old('education_ge') : '' }}{{ $news->education_ge or '' }}</textarea>

                                    </div>

                                    <div class="col-md-6 mt-2">

                                        <label>განათლება ინგლისურად</label>
                                        <textarea name="education_en" id="mymce" class="form-control">{{ old('education_en') ? old('education_en') : '' }}{{ $news->education_en or '' }}</textarea>

                                    </div>
                                </div>




                                <div class="row">
                                    <div class="col-md-6 mt-2">

                                        <label>Facebook პროფილის ლინკი</label>
                                        <input name="facebook" class="form-control" value="{{ old('facebook') ? old('facebook') : '' }}{{ $news->facebook or '' }}">

                                    </div>


                                    <div class="col-md-6 mt-2">

                                        <label>Instagram პროფილის ლინკი</label>
                                        <input name="instagram"  class="form-control" value="{{ old('instagram') ? old('instagram') : '' }}{{ $news->instagram or '' }}">

                                    </div>


                                    <div class="col-md-6 mt-2">

                                        <label>Twitter პროფილის ლინკი</label>
                                        <input name="twitter"  class="form-control" value="{{ old('twitter') ? old('twitter') : '' }}{{ $news->twitter or '' }}">

                                    </div>


                                    <div class="col-md-6 mt-2">

                                        <label>Youtube პროფილის ლინკი</label>
                                        <input name="youtube"  class="form-control" value="{{ old('youtube') ? old('youtube') : '' }}{{ $news->youtube or '' }}">

                                    </div>

                                </div>




                                <div class="row">
                                    @if(isset($form['id']))
                                        @if($news->picture!='')
                                            <div class="col-md-12 mt-5 mb-5">
                                                <label>სურათი</label>



                                                <div class="row">


                                                    <div class="col-md-4 p-2 mb-2" style="border:1px solid #efefef;border-radius:10px;">

                                                        <div class="btn btn-sm btn-danger mb-2 delete-majoritarians-picture"   x_id="{{ $news->id }}">წაშლა</div>
                                                        <img src="{{ asset('uploads/majoritarians') }}/{{ $news->picture }}" class="img-fluid">
                                                        <input type="text" name="image" hidden value="{{ $news->picture or '' }}">

                                                    </div>


                                                </div>
                                            </div>
                                        @endif
                                    @endif

                                    <div class="col-md-12 mt-2">

                                        <div id="my-majoritarian-files"  class="dropzone">



                                            <div class="fallback">
                                                <input name="file" type="file" multiple/>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="col-md-12 mt-3">
                                        <button class="btn btn-success">შენახვა</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @stop

        @section('javascript')
            <script>
                window.route_mass_crud_entries_destroy = '{{ route('admin.permissions.mass_destroy') }}';
            </script>
@endsection