routes/web.php
<?php

if (session()->get('locale') === null)
    session()->put('locale', App::getLocale());

Route::get('locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);

   // return redirect()->back()->with('lang', App::getLocale());
    $previousUrl = app('url')->previous();
    $exp=explode('?',$previousUrl);

    return redirect()->to($exp[0].'?'. http_build_query(['lang'=> $locale]));
});

Route::GET('transfer_data','ClientController@transfer_data');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


Route::GET('/','ClientController@index');
Route::GET('/about-party','ClientController@about');
Route::GET('/party-structure','ClientController@party_structure');
Route::GET('/party-council','ClientController@party_council');
Route::GET('/party-regulation','ClientController@party_regulation');
Route::GET('/bulletin','ClientController@bulletin');
Route::GET('/news','ClientController@news');
Route::GET('/candidates','ClientController@candidates');
Route::GET('/mayor','ClientController@mayor');
Route::GET('/show-mayor/{id}/{param}','ClientController@show_mayor');

Route::GET('/region-program','ClientController@region_program');
Route::GET('/show-region-program/{id}/{param}','ClientController@show_region_program');



Route::GET('/program','ClientController@program');
Route::GET('/world-media','ClientController@world_media');
Route::GET('/show-world-media/{id}/{param}','ClientController@show_world_media');
Route::GET('/show-candidates/{id}/{param}','ClientController@show_candidates');
Route::GET('/show-structure/{id}/{param}','ClientController@show_structure');

Route::GET('/video-gallery','ClientController@video_gallery');
Route::get('/show-photo-gallery/{id}','ClientController@show_photo_gallery');
Route::GET('/photo-gallery','ClientController@photo_gallery');
Route::GET('/contact','ClientController@contact');
Route::GET('/contact_send','ClientController@contact_send');

Route::GET('/young','ClientController@young');
Route::GET('/transfers','ClientController@transfers');
Route::GET('/search','ClientController@search');
Route::GET('/show-bulletin/{id}/{param}','ClientController@show_bulletin');

Route::GET('/show-news/{id}/{param}','ClientController@show_news');
Route::GET('/proportional','ClientController@proportional');
Route::GET('/show-bio/{id}/{param}','ClientController@show_bio');


Route::GET('/programs','ClientController@programs');


View::composer('website.layouts.app', function($view){
    $settings=\App\Models\DefaultSettingsModel::first();
    $view->with('settings',$settings);
});


Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);


    Route::POST('proportional_list/delete_proportional_list_picture','Admin\ProportionalController@delete_proportional_list_picture');
    Route::post('proportional_list/uploadFiles','Admin\ProportionalController@uploadFiles');
    Route::resource('proportional_list','Admin\ProportionalController');

    Route::POST('majoritarians/delete_majoritarians_picture','Admin\MajoritariansController@delete_majoritarians_picture');
    Route::post('majoritarians/uploadFiles','Admin\MajoritariansController@uploadFiles');
    Route::resource('majoritarians','Admin\MajoritariansController');


    Route::POST('mayor/delete_mayor_picture','Admin\mayorController@delete_mayor_picture');
    Route::post('mayor/uploadFiles','Admin\mayorController@uploadFiles');
    Route::resource('mayor','Admin\mayorController');


    Route::POST('region/get_districts','Admin\RegionController@get_districts');
    Route::POST('region/delete_district','Admin\RegionController@delete_district');
    Route::POST('region/update_district','Admin\RegionController@update_district');
    Route::POST('region/edit_district','Admin\RegionController@edit_district');
    Route::POST('region/save_district','Admin\RegionController@save_district');
    Route::get('region/add_district/{id}','Admin\RegionController@add_district');
    Route::resource('region','Admin\RegionController');

    Route::resource('default_settings','Admin\DefaultSettingsController');

    Route::POST('political_party/Sort','Admin\PoliticalPartyController@Sort');
    Route::POST('political_party/delete_politican_party_picture','Admin\PoliticalPartyController@delete_politican_party_picture');
    Route::POST('political_party/delete_other_position','Admin\PoliticalPartyController@delete_other_position');
    Route::POST('political_party/update_other_position','Admin\PoliticalPartyController@update_other_position');
    Route::POST('political_party/edit_other_position','Admin\PoliticalPartyController@edit_other_position');
    Route::POST('political_party/save_other_position','Admin\PoliticalPartyController@save_other_position');
    Route::GET('political_party/add_positions/{id}','Admin\PoliticalPartyController@add_positions');
    Route::post('political_party/uploadFiles','Admin\PoliticalPartyController@uploadFiles');
    Route::resource('political_party','Admin\PoliticalPartyController');

    Route::post('rules/uploadFiles','Admin\RulesController@uploadFiles');
    Route::resource('rules','Admin\RulesController');

    Route::post('about/uploadFiles','Admin\AboutController@uploadFiles');
    Route::resource('about','Admin\AboutController');


    Route::POST('media/delete_picture','Admin\MediaController@delete_picture');
    Route::POST('media/pin_home','Admin\MediaController@pin_home');
    Route::post('media/uploadFiles','Admin\MediaController@uploadFiles');
    Route::resource('media','Admin\MediaController');


    Route::POST('bulletin/pause-news','Admin\BulletinController@pause_news');
    Route::POST('bulletin/pin_to_slide','Admin\BulletinController@pin_to_slide');
    Route::POST('bulletin/delete_picture','Admin\BulletinController@delete_picture');
    Route::POST('bulletin/delete_attachment','Admin\BulletinController@delete_attachment');
    Route::POST('bulletin/pin_home','Admin\BulletinController@pin_home');
    Route::post('bulletin/uploadFiles','Admin\BulletinController@uploadFiles');
    Route::post('bulletin/uploadNewFiles','Admin\BulletinController@uploadNewFiles');
    Route::resource('bulletin','Admin\BulletinController');




    Route::POST('news/pause-news','Admin\NewsController@pause_news');
    Route::POST('news/pin_to_slide','Admin\NewsController@pin_to_slide');
    Route::POST('news/delete_picture','Admin\NewsController@delete_picture');
    Route::POST('news/delete_attachment','Admin\NewsController@delete_attachment');
    Route::POST('news/pin_home','Admin\NewsController@pin_home');
    Route::post('news/uploadFiles','Admin\NewsController@uploadFiles');
    Route::post('news/uploadNewFiles','Admin\NewsController@uploadNewFiles');
    Route::resource('news','Admin\NewsController');



    Route::POST('region_programe/pause-news','Admin\RegionPrograme@pause_news');
    Route::POST('region_programe/pin_home','Admin\RegionPrograme@pin_home');

    Route::POST('region_programe/delete_picture','Admin\RegionPrograme@delete_picture');
    Route::POST('region_programe/delete_attachment','Admin\RegionPrograme@delete_attachment');
    Route::post('region_programe/uploadFiles','Admin\RegionPrograme@uploadFiles');
    Route::post('region_programe/uploadNewFiles','Admin\RegionPrograme@uploadNewFiles');
    Route::resource('region_programe','Admin\RegionPrograme');


    Route::post('about/uploadFiles','Admin\AboutController@uploadFiles');
    Route::post('about/uploadHeaderFiles','Admin\AboutController@UploadHeaderFile');
    Route::resource('about','Admin\AboutController');

    Route::post('slider/uploadFiles','Admin\SliderController@uploadFiles');
    Route::resource('slider','Admin\SliderController');


    Route::post('transfers/uploadFiles','Admin\TransfersController@uploadFiles');
    Route::POST('transfers/uploadIconFiles','Admin\TransfersController@uploadIconFiles');
    Route::POST('transfers/delete_file','Admin\TransfersController@delete_file');
    Route::POST('transfers/delete_icon','Admin\TransfersController@delete_icon');
    Route::resource('transfers','Admin\TransfersController');


    Route::post('young/uploadFiles','Admin\YoungController@uploadFiles');
    Route::resource('young','Admin\YoungController');

    Route::POST('photo_gallery/delete_picture','Admin\PhotoGalleryController@delete_picture');
    Route::post('photo_gallery/uploadFiles','Admin\PhotoGalleryController@uploadFiles');
    Route::resource('photo_gallery','Admin\PhotoGalleryController');

app/Models/ProgramsModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;


class ProgramsModel extends Model
{
    protected $table='programs';
    protected $appends = [
        'file',
    ];
    public function getDescAttribute(){

        $langName = 'file_'.App::getLocale();

        return $this->$langName;
    }
}

resources/views/website/bulletin.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('website.layouts.app')

@section('content')





    <div class="news mt-3">
        <div class="container-custom" >



            <div class="row">
                <div class="col-md-12 pt-5 mb-3 mobile-margin-bottom-none mobile-padding-top-none margin-top-31-px">
                    <div class="col-12 p-0">
                        <div class="col-12">
                            <div class="row">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb bg-white">
                                        <li class="breadcrumb-item active" aria-current="page">
                                            {{--  <svg class="mr-3 mt-2" xmlns="http://www.w3.org/2000/svg" width="9.311" height="17.121" viewBox="0 0 9.311 17.121">
                                                  <path id="Path_215" data-name="Path 215" d="M7.5,7.5,15,15l7.5-7.5" transform="translate(-6.439 23.561) rotate(-90)" fill="none" stroke="#d0d0d0" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/></svg>
                                             --}}


                                            Bulletin
                                        </li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <div class="row">


            @foreach($news as $row)
                <!-- news -->
                    <div style="" class="col-12 mb-5 p-0 mobile-margin-bottom-none margin-bottom-30-px">
                        <div class="col-12">
                            <div class="col-12 p-0">
                                <div class="row">
                                    <div class="col-5 col-md-7 col-lg-7 col-xl-4 pr-0 pr-md-5">
                                        <a href="{{ url('show-bulletin') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->title) }}?lang={{ App::getLocale() == "ge" ? "ge" : "en" }}">

                                            @if(isset($row->Pictures->where('first_picture','1')->first()->picture))
                                                <img  class="img-fluid" src="{{ asset('uploads/bulletin') }}/{{ $row->Pictures->where('first_picture','1')->first()->picture }}">
                                            @else
                                                <img  class="img-fluid" src="{{ asset('uploads/bulletin') }}/{{ $row->Pictures->first()->picture }}">
                                            @endif

                                        </a>
                                    </div>
                                    <div class="col-7 col-md-5 col-lg-5 col-xl-8">
                                        <p class="mb-3 date-box-title">
                                            {{ $row->created_at->format('d') }}
                                            {{ $month[$row->created_at->format('m')] }},
                                            {{ $row->created_at->format('Y') }}
                                        </p>
                                        <a href="{{ url('show-bulletin') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->title) }}?lang={{ App::getLocale() == "ge" ? "ge" : "en" }}">
                                            <h1 class="mb-3 news-title">
                                                {{ $row->title }}
                                            </h1>
                                        </a>
                                        <div class=" d-none d-md-block">
                                            <a href="{{ url('show-bulletin') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->title) }}?lang={{ App::getLocale() == "ge" ? "ge" : "en" }}">

                                                <div class="news-description" style="    -webkit-line-clamp: 2;">
                                                    {!! strip_tags($row->desc) !!}
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- news -->
                @endforeach

                <div class="col-12">
                    <div class="">
                        <div class="col-12 margin-top-30-px margin-bottom-30-px p-0 d-block d-md-none">
                            <p class="b-t m-0"></p>
                        </div>
                    </div>
                </div>


                <div class="col-12 mt-5 pt-5 gd-pagination  b-t">
                    <div class="row">
                        <div class="col-12">
                            <nav class="" aria-label="Page navigation example">
                                <ul class="pagination d-flex align-items-center justify-content-center">
                                    @if ($news->onFirstPage())
                                        <li class="page-item mr-4">
                                            <a class="page-link previous" href="#">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="14.829" height="14.829" viewBox="0 0 14.829 14.829">
                                                    <g id="Icon_feather-arrow-down-right" data-name="Icon feather-arrow-down-right" transform="translate(7.414 12.829) rotate(-135)">
                                                        <path id="Path_211" data-name="Path 211" d="M0,7.657,7.657,0" fill="none" stroke="#b2b2b2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                        <path id="Path_212" data-name="Path 212" d="M7.657,7.657V0H0" fill="none" stroke="#b2b2b2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                    </g>
                                                </svg>
                                            </a>
                                        </li>
                                    @else
                                        <li class="page-item mr-4">
                                            <a class="page-link previous" href="{{ $news->previousPageUrl() }}">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="14.829" height="14.829" viewBox="0 0 14.829 14.829">
                                                    <g id="Icon_feather-arrow-down-right" data-name="Icon feather-arrow-down-right" transform="translate(7.414 12.829) rotate(-135)">
                                                        <path id="Path_211" data-name="Path 211" d="M0,7.657,7.657,0" fill="none" stroke="#4d81e2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                        <path  id="Path_212" data-name="Path 212" d="M7.657,7.657V0H0" fill="none" stroke="#4d81e2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                    </g>
                                                </svg>
                                            </a>
                                        </li>

                                    @endif



                                    <?php
                                    $start = $news->currentPage() - 1; // show 3 pagination links before current
                                    $end = $news->currentPage() + 3; // show 3 pagination links after current
                                    if($start < 1) {
                                        $start = 1; // reset start to 1
                                        $end += 1;
                                    }
                                    if($end >= $news->lastPage() ) $end = $news->lastPage(); // reset end to last page
                                    ?>


                                    @for ($i = $start; $i <= $end; $i++)

                                        @if($i==$request->page)

                                            <li class="page-item mr-2">
                                                <a class="page-link number page-active" href="{{ $news->url($i) }}">{{ $i }}</a>
                                            </li>
                                        @else

                                            <li class="page-item mr-2">
                                                <a class="page-link number" href="{{ $news->url($i) }}">{{ $i }}</a>
                                            </li>
                                        @endif



                                    @endfor





                                    @if ($news->hasMorePages())
                                        <li class="page-item">
                                            <a class="page-link next" href="{{ $news->nextPageUrl() }}#">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="14.829" height="14.829" viewBox="0 0 14.829 14.829">
                                                    <g id="Icon_feather-arrow-down-right" data-name="Icon feather-arrow-down-right" transform="translate(2 7.415) rotate(-45)">
                                                        <path id="Path_211" data-name="Path 211" d="M10.5,10.5l7.657,7.657" transform="translate(-10.5 -10.5)" fill="none" stroke="#4d81e2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                        <path id="Path_212" data-name="Path 212" d="M18.157,10.5v7.657H10.5" transform="translate(-10.5 -10.5)" fill="none" stroke="#4d81e2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                    </g>
                                                </svg>
                                            </a>
                                        </li>
                                    @else
                                        <li class="page-item">
                                            <a class="page-link next" href="#">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="14.829" height="14.829" viewBox="0 0 14.829 14.829">
                                                    <g id="Icon_feather-arrow-down-right" data-name="Icon feather-arrow-down-right" transform="translate(2 7.415) rotate(-45)">
                                                        <path id="Path_211" data-name="Path 211" d="M10.5,10.5l7.657,7.657" transform="translate(-10.5 -10.5)" fill="none" stroke="#4d81e2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                        <path id="Path_212" data-name="Path 212" d="M18.157,10.5v7.657H10.5" transform="translate(-10.5 -10.5)" fill="none" stroke="#4d81e2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
                                                    </g>
                                                </svg>
                                            </a>
                                        </li>

                                    @endif

                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                <!-- pagination -->
            {{-- <div class="col-12 pt-5 gd-pagination d-none d-md-block">
                 <div class="row">
                     <div class="col-12">
                         {{  $news->appends(request()->input())->links("pagination::bootstrap-4") }}

                     </div>
                 </div>
             </div>--}}
            <!-- pagination -->


            </div>

        </div>
    </div>


@stop

resources/views/website/party_structure.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('website.layouts.app')

@section('content')

    <div class="structure mt-3">
        <div class="container-custom mb-5">
            <div class="row">

                <div class="col-md-12 pt-5 mb-3 mobile-margin-bottom-none mobile-padding-top-none margin-top-31-px">
                    <div class="col-12 p-0">
                        <div class="col-12">
                            <div class="row">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb bg-white pl-0">
                                        <li class="breadcrumb-item_other active" aria-current="page"> @lang('site.party') <svg class="ml-3 mr-3" xmlns="http://www.w3.org/2000/svg" width="9.311" height="17.121" viewBox="0 0 9.311 17.121"><path id="Path_215" data-name="Path 215" d="M7.5,7.5,15,15l7.5-7.5" transform="translate(-6.439 23.561) rotate(-90)" fill="none" stroke="#d0d0d0" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/></svg> </li>
                                        <li class="breadcrumb-item_other active" aria-current="page">  @lang('site.structure') </li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 margin-top-50-px">
                    <div class="row">


                        @foreach($party_structure as $row)

                        <!-- column -->
                        <div class="col-12 col-lg-6 p-0">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body pt-0 pr-0 pl-0 pb-0">
                                        <div class="row">
                                            <div class="col-7">
                                                <div class="d-block d-md-none structure-detail mb-2"></div>
                                                <a href="{{ url('show-structure') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->name) }}">
                                                <h5 class="card-title structure-title">
                                                    {{$row->name}}
                                                </h5>
                                                </a>
                                                <p class="card-text political-desc">{{ $row->position }}</p>
                                                <div class="d-none d-md-block down">
                                                    <a class="d-flex align-items-center" href="{{ url('show-structure') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->name) }}">
                                                        <div class="biography">@lang('site.biography')</div>
                                                        <img class="downarrow" src="{{ url('website') }}/images/icondownarrow.png"></a>
                                                </div>
                                            </div>
                                            <div class="col-5">
                                                <a href="{{ url('show-structure') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->name) }}">

                                                <img  src="{{ asset('uploads/political_party') }}/{{ $row->picture }}" alt="sans" class="img-fluid">
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 margin-top-30-px margin-bottom-30-px p-0 d-block d-md-none">
                                    <p class="b-t m-0"></p>
                                </div>
                                <div class="col-12 pt-40 pl-0 pr-0 mb-60 d-none d-md-block">
                                    <p class="b-t m-0"></p>
                                </div>
                            </div>
                        </div>
                        <!-- column -->
                        @endforeach






                    </div>
                </div>

            </div>
        </div>
    </div>

@stop

resources/views/website/world_media.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('website.layouts.app')

@section('content')





    <div class="news mt-3">
        <div class="container-custom" >



            <div class="row">
                <div class="col-md-12 pt-5 mb-3 mobile-margin-bottom-none mobile-padding-top-none margin-top-31-px">
                    <div class="col-12 p-0">
                        <div class="col-12">
                            <div class="row">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb bg-white">
                                        <li class="breadcrumb-item active" aria-current="page">
                                           {{-- <svg class="mr-3 mt-2" xmlns="http://www.w3.org/2000/svg" width="9.311" height="17.121" viewBox="0 0 9.311 17.121">
                                                <path id="Path_215" data-name="Path 215" d="M7.5,7.5,15,15l7.5-7.5" transform="translate(-6.439 23.561) rotate(-90)" fill="none" stroke="#d0d0d0" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/></svg>
                                            --}}

                                            @lang('site.world-media')
                                        </li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <div class="row">



            @foreach($news as $row)
                <!-- news -->
                    <div class="col-12 mb-5 p-0 mobile-margin-bottom-none margin-bottom-30-px">
                        <div class="col-12">
                            <div class="col-12 p-0">
                                <div class="row">
                                    <div class="col-5 col-md-7 col-lg-7 col-xl-4 pr-0 pr-md-5">
                                        <a href="{{ url('show-world-media') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->title) }}">
                                            <img  class="img-fluid" src="{{ asset('uploads/media') }}/{{ $row->Pictures->where('first_picture','1')->first()->picture }}">

                                        </a>
                                    </div>
                                    <div class="col-7 col-md-5 col-lg-5 col-xl-8">
                                        <p class="mb-3 date-box-title">
                                            {{ $row->created_at->format('d') }}
                                            {{ $month[$row->created_at->format('m')] }},
                                            {{ $row->created_at->format('Y') }}
                                        </p>
                                        <a href="{{ url('show-world-media') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->title) }}">
                                            <h1 class="mb-3 news-title">
                                                {{ $row->title }}
                                            </h1>
                                        </a>
                                        <div class=" d-none d-md-block">
                                        <a href="{{ url('show-world-media') }}/{{ $row->id }}/{{ str_replace(' ', '-', $row->title) }}">

                                            <div class="news-description" style="    -webkit-line-clamp: 2;">
                                                {!! strip_tags($row->desc) !!}
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <!-- news -->
            @endforeach

            <div class="col-12">
                <div class="">
                    <div class="col-12 margin-top-30-px margin-bottom-30-px p-0 d-block d-md-none">
                        <p class="b-t m-0"></p>
                    </div>
                </div>
            </div>

            <!-- pagination -->
            <div class="col-12 pt-5 gd-pagination d-none d-md-block">
                <div class="row">
                    <div class="col-12">
                        {{  $news->appends(request()->input())->links("pagination::bootstrap-4") }}

                    </div>
                </div>
            </div>
            <!-- pagination -->


        </div>

    </div>
    </div>


@stop